name: hyperch4
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - matplotlib>=3.8.0
  # - proplot, # pip install git+https://github.com/cvanelteren/proplot.git@mpl3.8 --user
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - scipy
  - xarray
  - cfgrib
  - h5netcdf
  - rioxarray
  - pyresample
  - contextily
  - folium
  - enpt
  - satpy
  - algotom
  - dem_stitcher
  - aiohttp
  # - spacetrack  # pip install spacetrack
