name: hypergas
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - matplotlib>=3.8.0
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - scipy
  - xarray
  - cfgrib
  - h5netcdf
  - rioxarray
  - pyresample
  - contextily
  - folium
  - enpt
  - satpy
  - algotom
  - dem_stitcher
  - aiohttp
  - roaring-landmask
  # - spacetrack  # pip install spacetrack
