name: hypergas
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - matplotlib>=3.8.0
  - numpy
  - pandas
  - scikit-learn
  - scikit-image>=0.24.0
  - scipy
  - xarray
  - cfgrib
  - h5netcdf
  - rioxarray
  - pyresample
  - contextily
  - folium
  - enpt>=0.21.1
  - satpy
  - algotom
  - dem_stitcher
  - aiohttp
  - tobac
  - streamlit
  - matplotlib-scalebar
  # - spacetrack  # pip install spacetrack
