name: readthedocs
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - matplotlib>=3.8.0
  - numpy
  - pandas
  - scikit-learn
  - scikit-image>=0.24.0
  - scipy
  - xarray
  - cfgrib
  - h5netcdf
  - rioxarray
  - pyresample
  - contextily
  - folium
  - satpy
  - dem_stitcher
  - streamlit
  - matplotlib-scalebar
  - setuptools
  - setuptools_scm
  - sphinx>=8.2.0
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - sphinxcontrib-apidoc
  - pip:
      - spacetrack
      - spectral
      - . # relative path to the hypergas project
