data:
  # dir paths will be set as a relative path to hyperch4 package
  absorption_dir:
    resources/absorption
  irradiance_dir:
    resources/solar_irradiance
  modtran_dir:
    resources/modtran_full
  rgb_dir:
    resources/rgb
  era5_dir:
    # data structure should be: yyyy/sl*grib
    # if you leave this empty, the package will try to load cloud data (not supported yet)
    resources/ERA5
  geosfp_dir:
    # data structure should be: yyyy/mm/dd/GEOS.fp.asm.tavg1_2d_slv_Nx.*.V01.nc4
    # if you leave this empty, the package will try to load cloud data (not supported yet)
    resources/GEOS-FP
  markers_filename:
    # the csv file which saves pre-defined markers
    #   it should contains at least two columns: "latitude" and "longitude"
    #   the `l2b_plot.py` will add CircleMarkers on Map and click it to see correcponding DataFrame info
    resources/markers/markers.csv
  spacetrack_usename:
    <username>
  spacetrack_password:
    <password>

species:
  ch4:
    name: methane
    wavelength: [2110, 2450]
    full_wavelength: [1300, 2500]
    rad_source: model  # "model" or "lut", note that "lut" only supports ch4 and co2
    concentrations: [0, 0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4]  # for rad_source=="model", units: ppm
    # concentrations: [0.0e+3, 1.0e+3, 2.0e+3, 4.0e+3, 8.0e+3, 1.6e+4, 3.2e+4, 6.4e+4]  # for rad_source=="lut", units: ppm m
    units: ppb  # units of output product
  co2:
    name: carbon dioxide
    wavelength: [1930, 2200]
    full_wavelength: [1300, 2500]
    rad_source: model
    concentrations: [0, 2.5, 5.0, 10.0, 20.0, 40.0, 80.0, 160.0]  # for rad_source=="model", units: ppm
    # concentrations: [0.0e+4, 2.0e+4, 4.0e+4, 8.0e+4, 1.6e+5, 3.2e+5, 6.4e+5, 1.28e+6] # for rad_source=="lut", units: ppm m
    units: ppm
  no2:
    name: nitrogen dioxide
    wavelength: [400, 500]
    full_wavelength: [400, 700]
    rad_source: model
    concentrations: [0.0e-5, 2.900e-5, 5.800e-5, 1.160e-4, 2.320e-4, 4.640e-4, 9.280e-4, 1.856e-3]
    # np.array([0, 10.0, 20.0, 40.0, 80.0, 160.0, 320.0, 640.0])*2.9*1e-6  # umol m-2 --> ppm
    units: umol m-2

