# dir paths will be set as a relative path to hyperch4 package
absorption_dir:
  resources/absorption
irradiance_dir:
  resources/solar_irradiance
modtran_dir:
  resources/modtran_full
rgb_dir:
  resources/rgb
era5_dir:
  # data structure should be: yyyy/sl*grib
  # if you leave this empty, the package will try to load cloud data (not supported yet)
  resources/ERA5
geosfp_dir:
  # data structure should be: yyyy/mm/dd/GEOS.fp.asm.tavg1_2d_slv_Nx.*.V01.nc4
  # if you leave this empty, the package will try to load cloud data (not supported yet)
  resources/GEOS-FP
markers_filename:
  # the csv file which saves pre-defined markers
  #   it should contains at least two columns: "latitude" and "longitude"
  #   the `l2b_plot.py` will add CircleMarkers on Map and click it to see correcponding DataFrame info
  resources/markers/markers.csv
spacetrack_usename:
  <username>
spacetrack_password:
  <password>

